language: generic

sudo: required

services:
- docker

install: true

stages:
- build-and-test

matrix:
  include:
    - stage: build-and-test
      env: fedora=rawhide
    - stage: build-and-test
      env: fedora=30
    - stage: build-and-test
      env: fedora=29
    - stage: build-and-test
      env: fedora=28

before_script:
- if test -n "$fedora" ; then sed -i "s#^FROM.*#FROM registry.fedoraproject.org/fedora:$fedora#" tests/Dockerfile ; fi

script:
- docker build -t python-libssh -f tests/Dockerfile .
- docker run --name python-libssh --rm -d python-libssh
- docker exec python-libssh python3 setup.py test
