name: Build and test python-libssh

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '38 4 5 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - registry.fedoraproject.org/fedora:latest
          - registry.fedoraproject.org/fedora:rawhide
    steps:
      - uses: actions/checkout@v4
      - name: Set the right OS in the Dockerfile
        run: sed -i "s#^FROM.*#FROM ${{ matrix.os }}#" tests/Dockerfile
      - name: Build image
        run: docker build -t python-libssh -f tests/Dockerfile .
      - name: Run container
        run: docker run --name python-libssh --rm -d python-libssh
      - name: Run tests with unittest discover
        run: docker exec python-libssh python3 -m unittest discover -v -s tests -p 't*_*.py'
      - name: Run tests manually
        run: docker exec python-libssh bash -c 'cp -rp tests /tmp/tests && cd /tmp/tests && for i in *.py ; do python3 -Werror $i ; done'
