name: Build and test python-libssh

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '38 4 5 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-latest, fedora-rawhide ]
    steps:
      - uses: actions/checkout@v2
      - name: Set the right OS in the Dockerfile
        run: sed -i "s#^FROM.*#FROM $( echo ${{ matrix.os }} | sed 's#^fedora-#registry.fedoraproject.org/fedora:#' )#" tests/Dockerfile
      - name: Build image
        run: docker build -t python-libssh -f tests/Dockerfile .
      - name: Run container
        run: docker run --name python-libssh --rm -d python-libssh
      - name: Run tests in the container
        run: docker exec python-libssh python3 setup.py test
      - name: Run tests with installed rpm
        run: docker exec python-libssh bash -c 'cp -rp tests /tmp/tests && cd /tmp/tests && for i in *.py ; do python3 $i ; done'
