name: Build and test python-libssh

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '38 4 5 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - registry.fedoraproject.org/fedora:latest
          - registry.fedoraproject.org/fedora:rawhide
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set the right OS in the Dockerfile
        run: sed -i "s#^FROM.*#FROM ${{ matrix.os }}#" tests/Dockerfile
      - name: Disable AppArmor for unix-chkpwd
        run: sudo ln -s /etc/apparmor.d/unix-chkpwd /etc/apparmor.d/disable/ && sudo apparmor_parser -R /etc/apparmor.d/unix-chkpwd
      - name: Build image
        run: podman build --env SOURCE_DATE_EPOCH=$( date '+%s' -d $( git show --pretty='tformat:%cI' -s HEAD ) ) -t python-libssh -f tests/Dockerfile .
      - name: Run container
        run: podman run --name python-libssh --rm -d python-libssh
      - name: Run tests with unittest discover
        run: podman exec python-libssh python3 -m unittest discover -v -s tests -p 't*_*.py'
      - name: Run tests manually
        run: podman exec python-libssh bash -c 'cp -rp tests /tmp/tests && cd /tmp/tests && for i in *.py ; do python3 -Werror $i ; done'
